apiVersion: v1
kind: Service
metadata:
  name: auction-service
  namespace: default
spec:
  selector:
    io.kompose.service: auction-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083