apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.31.0 (a04ecdb9e)
  creationTimestamp: null
  labels:
    io.kompose.service: auction-service
  name: auction-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: auction-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.31.0 (a04ecdb9e)
      creationTimestamp: null
      labels:
        io.kompose.network/pawn-auction-system: "true"
        io.kompose.service: auction-service
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: auction_db
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_PASSWORD
              value: root_password
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
          image: jxlok/pawn-auction-service:1.0
          imagePullPolicy: Always
          name: pawn-auction-service
          resources: {}
      hostname: auction-service
      restartPolicy: Always
status: {}
