apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-service-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bid-service-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bid-service-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine3.17-slim
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
