apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.31.0 (a04ecdb9e)
  creationTimestamp: null
  labels:
    io.kompose.service: bid-service
  name: bid-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: bid-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.31.0 (a04ecdb9e)
      creationTimestamp: null
      labels:
        io.kompose.network/pawn-auction-system: "true"
        io.kompose.service: bid-service
    spec:
      containers:
        - image: jxlok/pawn-bid-service:1.0
          name: pawn-bid-service
          resources: {}
      hostname: bid-service
      restartPolicy: Always
status: {}
