apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.31.0 (a04ecdb9e)
  creationTimestamp: null
  labels:
    io.kompose.service: bid-service-nginx
  name: bid-service-nginx
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    io.kompose.service: bid-service-nginx
  type: NodePort
status:
  loadBalancer: {}
