apiVersion: v1
kind: Service
metadata:
  name: bid-service-nginx
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: bid-service-nginx
  type: NodePort