apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: default
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: apache/kafka:3.7.0
          ports:
            - containerPort: 9092
              hostPort: 9092
              protocol: TCP
            - containerPort: 19092
              protocol: TCP
          env:
            - name: CLUSTER_ID
              value: 4L6g3nShT-eMCtK--X86sw
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT_HOST://localhost:9092,PLAINTEXT://broker:19092
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@broker:29093
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_LISTENERS
              value: CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_LOG_DIRS
              value: /tmp/kraft-combined-logs
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: broker,controller
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
          resources: {}
      hostname: broker
      restartPolicy: Always
status: {}