apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: default
  labels:
    app: broker
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "19092"
      port: 19092
      targetPort: 19092
  selector:
    app: broker
status:
  loadBalancer: {}
