apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.31.0 (a04ecdb9e)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
  namespace: default
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "19092"
      port: 19092
      targetPort: 19092
  selector:
    io.kompose.service: broker
status:
  loadBalancer: {}
