apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.31.0 (a04ecdb9e)
  creationTimestamp: null
  labels:
    io.kompose.network/pawn-auction-system: "true"
    io.kompose.service: init-kafka
  name: init-kafka
  namespace: default
spec:
  containers:
    - args:
        - |2
          # blocks until kafka is reachable
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:19092 --list

          echo -e 'Creating kafka topics'
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:19092 --create --if-not-exists --topic pawn.auction.bids --replication-factor 1 --partitions 1
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:19092 --create --if-not-exists --topic pawn.auction.updates --replication-factor 1 --partitions 1

          echo -e 'Successfully created the following topics:'
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:19092 --list
      command:
        - sh
        - -c
      image: apache/kafka:3.7.0
      name: init-kafka
      resources: {}
  hostname: init-kafka
  restartPolicy: Never
status: {}
