apiVersion: v1
kind: Pod
metadata:
  name: init-kafka
  namespace: default
spec:
  containers:
    - name: init-kafka
      image: apache/kafka:3.7.0
      command:
        - sh
        - -c
        - |
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:19092 --list
          echo 'Creating kafka topics'
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:19092 --create --if-not-exists --topic pawn.auction.bids --replication-factor 1 --partitions 1
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:19092 --create --if-not-exists --topic pawn.auction.updates --replication-factor 1 --partitions 1
          echo 'Successfully created the following topics:'
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server broker:19092 --list
      resources: {}
  restartPolicy: Never
